#!/bin/sh

# Generates the autotools stuff.  E.g. ./configure


PROMPT="  [$0]$"
autotools_stuff="aclocal.m4 config.h.in autom4te.cache configure missing
                 install-sh Makefile.in src/Makefile.in
                 src/switchbox/Makefile.in build-aux README DESIGN COPYING
                 NEWS AUTHORS INSTALL ChangeLog"

if [ $1 ] # If there are arguments
then
    if [ $1 != clean ]; then echo invalid command; exit; fi

    echo "Cleaning up symbolic links:"
    echo "$PROMPT" rm -f README DESIGN
    rm -f README DESIGN
    echo

    echo "Cleaning up autotools temporary files:"
    echo "$PROMPT" rm -rf $autotools_stuff
    rm -rf $autotools_stuff

else
    echo "Generating autotools stuff:"
    echo "$PROMPT" generating README DESIGN COPYING NEWS ChangeLog and AUTHORS
    if [ ! -e README ]; then ln -s doc/readme.rst README; fi
    if [ ! -e DESIGN ]; then ln -s doc/design.rst DESIGN; fi
    if [ ! -e COPYING ]; then ln -s doc/copyright.rst COPYING; fi
    if [ ! -e AUTHORS ]; then ln -s doc/authors.rst AUTHORS; fi
    if [ ! -e NEWS ]; then ln -s doc/news.rst NEWS; fi
    if [ ! -e ChangeLog ]; then ln -s doc/changes.rst ChangeLog; fi

    echo "$PROMPT" autoreconf --install
    autoreconf --install
fi
