#!/bin/sh

# Generates the autotools stuff.  E.g. ./configure

PROMPT="  [$0]$"
infiles=`find . -name Makefile.in`
autotools_stuff="aclocal.m4 autom4te.cache configure missing install-sh
                 build-aux depcomp doc/Makefile ltmain.sh config.sub
                 config.guess doc/doxygen $infiles py-compile
                 m4/ltsugar.m4 m4/libtool.m4 m4/ltversion.m4 m4/lt~obsolete.m4
                 m4/ltoptions.m4"

if [ $1 ] # If there are arguments
then
    if [ $1 != clean ]; then echo invalid command; exit; fi

    echo "Cleaning up autotools temporary files:"
    echo "$PROMPT" rm -rf $autotools_stuff
    rm -rf $autotools_stuff

else
    echo "Generating autotools stuff:"
    echo "$PROMPT" autoreconf --install
    autoreconf --install
fi
