* Ideas
  This is for long-term, loosely-specified, rough-ideas of features
  that maybe might be worth implementing eventually.

** TODO Regenerating Persistent Maps
** TODO Portals Between Different Servers
** TODO Screen position not fixed
   Standing at the edge, you can only aim towards the middle of the
   map.  To fix this there screen should center around the player
   somehow.

** TODO No Special Rules For Different Directions
   Right now left-right wraps and top-down kills.  This is complicated
   an not general.  I.E. a map with no gravity-wind but a big
   attractor in the middle should have the same rules for all sides.
   However, it's not clear which rules to enact.

*** Kill-Zones Instead of Death-at-Edges
    We could make all sides wrap, but have kill-zones placed at the
    edges of some sides.  You don't really want to die right at the
    edge, so maybe we could make the game-space separate from the
    map-files somehow?  I can't think of a clean way to do this right
    now.
