#!/bin/awk -f

BEGIN {
	print "\
proc shift {x y} {\n\
	lassign $::playerpos X Y\n\
	incr X $x; incr Y $y\n\
	set ::playerpos [list $X $Y] }" }
/^up$/ { print "shift 0 -10" }
/^down$/ { print "shift 0 10" }
/^left$/ { print "shift -10 0" }
/^right$/ { print "shift 10 0" }
/^shoot [0-9]* [0-9]*$/ { print "explode 40 " $2 " " $3 }
{ print $0 > "/dev/stderr"; fflush() }
