#!/bin/awk -f

/^up$/ { print "shift .c3 0 -10"; }
/^down$/ { print "shift .c3 0 10" }
/^left$/ { print "shift .c3 -10 0" }
/^right$/ { print "shift .c3 10 0" }
/^shoot [0-9]* [0-9]*$/ { print "explode 40 " $2 " " $3 }
{ print $0 > "/dev/stderr"; fflush() }
