<$PLAN9/src/mkhdr

MKSHELL = /bin/bash
SDL = -lSDL_image -lSDL_gfx -lSDL_mixer
LDFLAGS = -ltcl8.5 -lm $SDL
CFLAGS = -Os --std=gnu99 -Wall -Werror -pedantic
TARG = sdlsh

all:V:
o.sdlsh: draw.o keys.o
sdlsh.o: draw.h keys.h macro.h
draw.o: draw.h macro.h
keys.o: keys.h macro.h

<$PLAN9/src/mkmany

test:V: all
	export SDLSH_ROOT=.
	sixty-nine './o.sdlsh test.tcl' ./comm-test
