#!/bin/sh

find_file_up_tree() {
  [ $# = 1 ] || exit 1
  target_filename=$1
  search_dir=$PWD

  while [ 1 ]
  do
    target=$search_dir/$target_filename
    [ $search_dir = '/' ] && target="/$target_fileanme"
    if [ -e $target ]; then echo $target; exit; fi
    [ $search_dir = '/' ] && exit 1
    search_dir=`dirname $search_dir`
  done
}

proot=`dirname \`find_file_up_tree Project\``
pfile=$proot/Project

custom_command () {
  [ $# = 1 ] || exit 1

  command=$1
  awk="\$2 == \"$command\" {for(i=4;i<=NF;i++) printf \"%s \", \$i}"
  command=`awk "\\$2 == \\"$command\\" {for(i=4;i<=NF;i++) printf \\"%s \\", \\$i}" < $pfile`
  echo running $command at $proot
  cd $proot
  eval $command
}


invoke=`basename $0`

if [ $invoke = "proot" ]; then echo $proot; fi
if [ $invoke = "pclean" ]; then custom_command clean; fi
if [ $invoke = "psetup" ]; then custom_command setup; fi
if [ $invoke = "pbuild" ]
then 
     [ -e $proot/Makefile ] || custom_command setup
     custom_command build
fi
